services:
# mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - type: volume
        source: mariadb_volume
        target: /var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
# nginx
  nginx:
    image: nginx:user
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - type: volume
        source: wordpress_volume
        target: /var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
# wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - type: volume
        source: wordpress_volume
        target: /var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always

# volume
volumes:
  mariadb_volume:
    name: mariadb_volume
  wordpress_volume:
    name: wordpress_volume

# network
networks:
  inception:
    name: inception
